# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_history"
version = "1.0.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "Input History Editor"
categories = ["command history"]
keywords = ["fortran", "input editing"]
homepage = "https://github.com/urbanjost/M_history.git"

[build]
   module-naming = true

[[test]]
name="test_suite_M_history"
source-dir="test"
main="test_suite_M_history.f90"
[test.dependencies]
M_framework = { git = "https://github.com/urbanjost/M_framework.git" }
#M_framework = {namespace = "GPF"}
